### ISSUE TITLE
--generate_config not working properly

### ISSUE THREAD

**Issue by muzgash** [colav/HunabKu#420]
Installed hunabku as root. Proceeded with the suggested command:

hunabku_server --generate_config config.py --overwrite

And got the following traceback:

Traceback (most recent call last):
  File "/usr/local/bin/hunabku_server", line 3, in <module>
    from hunabku.HunabkuBase import set_verbose
  File "/usr/local/lib/python3.8/dist-packages/hunabku/__init__.py", line 2, in <module>
    from hunabku import Hunabku
  File "/usr/local/lib/python3.8/dist-packages/hunabku/Hunabku.py", line 8, in <module>
    from hunabku.HunabkuBase import HunabkuPluginBase
  File "/usr/local/lib/python3.8/dist-packages/hunabku/HunabkuBase.py", line 8, in <module>
    from hunabku.Config import Config
  File "/usr/local/lib/python3.8/dist-packages/hunabku/Config.py", line 6, in <module>
    class Config:
  File "/usr/local/lib/python3.8/dist-packages/hunabku/Config.py", line 62, in Config
    def keys(self) -> list[str]:
TypeError: 'type' object is not subscriptable

**Comment by omazapa** [comment]
Hi @muzgash 
do you have any plugins installed?
if yes, can you share that code with me?
